### ISSUE TITLE
Bootloop

### ISSUE THREAD

**Issue by lodestone41** [Dyneteve/firplay_xiaomi_apollo#12]
Hi i've had bootloop issues. I cleared through that using fastboot and clearing cache. Yet now my camera wont focus and the wifi won't activate. This all started when i attempted the latest update. 
Edit1: I've tried the update once again it says update error.
Edit2: I've just tried a factory reset and it landed in another bootloop. Got out of that using the "fastboot clear cache". This still leaves me where i was. I can't escape the bootloop for anything else but to get back to where i am. I want to upgrade to the new rom but don't know how. Magisk has also been uninstalled somehow.

**Comment by Dyneteve** [comment]
@lodestone41 Edit3 lol
