### ISSUE TITLE
slow pubg

### ISSUE THREAD

**Issue by puuska** [Dyneteve/firplay_xiaomi_apollo#30]
only 59 fps pubg i want 60 bad karmel noob dev

**Comment by ghost** [comment]
Same here hapl

**Comment by Dyneteve** [comment]
@puuska Agreed! We need more overclock as per https://github.com/Dyneteve/firplay_xiaomi_apollo/commit/9f95c8d9aeb80400776aa9a4af47b347c03209dc this is solved
